sudo: required
language: ruby
services:
  - docker

before_install:
- git clone https://github.com/uyuni-project/uyuni-docs
- cd uyuni-docs/
- git checkout gh-pages
- rm -rf *
- git clone git@github.com:uyuni-project/uyuni-docs-publisher.git
- cd uyuni-docs-publisher
- docker pull antora/antora
- docker images
- docker run -u $UID -v `pwd`:/antora --rm -t antora/antora --cache-dir=./.cache/antora uyuni-publisher.yml
- cp -r public/* ../../
